name: albertina
title: Albertina
base: core24
version: "0.1.0"
contact: gatochalupa@gmail.com
website: https://gatochalupa.com
source-code: https://codeberg.org/GatoChalupa/albertina
issues: https://codeberg.org/GatoChalupa/albertina/issues
license: MIT
donation: https://liberapay.com/lapisdecor/donate

summary: A personal dictionary for personal definitions.
description: |
  Albertina is a simple personal dictionary application built with Nim, Owlkettle (GTK4), and SQLite. It can also be used as a notebook.

icon: snap/gui/albertina.png
grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

lint:
  ignore:
    - library:
        - usr/lib/*/libsqlite3.so.*

apps:
  albertina:
    command: bin/albertina
    extensions: [gnome]
    plugs:
      - home
      - network
    #desktop: snap/gui/albertina.desktop
    common-id: com.gatochalupa.albertina

parts:
  albertina:
    plugin: nil
    source: .
    build-packages:
      - curl
      - gcc
      - git
      - libsqlite3-dev
      - libgtk-4-dev
      - libadwaita-1-dev
    stage-packages:
      - libsqlite3-0
    override-build: |
      set -e
      case "$CRAFT_ARCH_BUILD_ON" in
        amd64) NIM_ARCH=linux_x64 ;;
        arm64) NIM_ARCH=linux_arm64 ;;
      esac
      curl https://nim-lang.org/download/nim-2.2.12-${NIM_ARCH}.tar.xz -sSf -o nim.tar.xz
      tar -xJf nim.tar.xz
      export PATH=$CRAFT_PART_SRC/nim-2.2.12/bin:$PATH
      nim c -d:release --hints:off -o:albertina src/albertina.nim
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp albertina $CRAFT_PART_INSTALL/bin/
      #mkdir -p $CRAFT_PART_INSTALL/snap/gui
      #cp snap/gui/albertina.desktop $CRAFT_PART_INSTALL/snap/gui/
      #cp snap/gui/albertina.png $CRAFT_PART_INSTALL/snap/gui/
